stages:
    - build
    - deploy

before_script:
    - mix local.hex --force
    - mix local.rebar

variables:
    APPLICATION_NAME: astarte_data_access

mix:test-ci:
    image: elixir:1.6.5
    services:
        - cassandra:3.11.2
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
    cache:
        paths:
            - deps
    except:
        - branches@Astarte-NG/astarte_data_access

mix:build:
    image: elixir:1.6.5
    services:
        - cassandra:3.11.2
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
    cache:
        paths:
            - deps
    only:
        - master@Astarte-NG/astarte_data_access

mix:release-build:
    image: elixir:1.6.5
    services:
        - cassandra:3.11.2
    stage: build
    script:
        - export MIX_ENV=test
        - mix deps.get
        - mix deps.compile
        - mix compile
        - mix coveralls
    cache:
        paths:
            - deps
    only:
        - tags@Astarte-NG/astarte_data_access
